FROM mysql
ENV MYSQL_ROOT_PASSWORD MYSQL_ROOT_PASSWORD
ENV MYSQL_DATABASE ku1_newsletter_messenger
ENV MYSQL_USER ku1-newsletter-messenger-user
ENV MYSQL_PASSWORD ku1-newsletter-user-messenger-Pa5Sw0rD!!!