#Telegram bot token
botToken = "5793483632:AAHcsmlLhCau1qpF4k4YJ2EP0CMahGqvOJc"
#Mysql container name and port
dbAddress = "ku1-newsletter-messenger-mysql:3306"
dbName = "ku1_newsletter"
dbUsername = "root"
dbPassword = "MYSQL_ROOT_PASSWORD"