version: '3'
services:
    #Message sender
    ku1-newsletter-messenger-api:
        container_name: ku1-newsletter-messenger-api
        image: golang
        restart: always
        depends_on:
            - ku1-newsletter-messenger-mysql
        volumes:
            - ../:/usr/src/ku1-newsletter-messenger
        working_dir: /usr/src/ku1-newsletter-messenger
        entrypoint: go run cmd/api/main.go -config=config/local.toml
    #Users registrator
    ku1-newsletter-messenger-bot:
        container_name: ku1-newsletter-messenger-bot
        image: golang
        restart: always
        depends_on:
            -   ku1-newsletter-messenger-mysql
        volumes:
            - ../:/usr/src/ku1-newsletter-messenger
        working_dir: /usr/src/ku1-newsletter-messenger
        entrypoint: go run cmd/bot/main.go -config=config/local.toml
    #Database
    ku1-newsletter-messenger-mysql:
        container_name: ku1-newsletter-messenger-mysql
        build:
            context: database
            dockerfile: Dockerfile
        restart: always
        volumes:
            -   ../../ku1-newsletter-messenger-database:/var/lib/mysql
        ports:
            - 3316:3306

networks:
    bridge:
        external: true